### ISSUE TITLE
Review of Travis-CI configuration is required

### ISSUE THREAD

**Issue by tsuchm** [emacs-w3m/emacs-w3m#11]
I have just added Travis-CI configuration to do automatic syntax check for every pull requests.   However, I wonder whether I successfully configured it as the free plan for open source projects or not.   If you have an information to check it, please let me know.

**Comment by tsuchm** [comment]
You may see the Travis CI results at https://travis-ci.com/emacs-w3m/emacs-w3m

**Comment by Boruch-Baum** [comment]
This isn't something I know anything about, although on other projects I've often been a _victim_ of Travis, and it pretty much always turns out to be a mis-configuration.

**Comment by tsuchm** [comment]
I found a document at https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/, and then I believe that this repository uses the free version of travis-ci.com.

However, I still have a problem that automatic build for pull requests does not work as shown in https://travis-ci.com/emacs-w3m/emacs-w3m/pull_requests.
I need this feature to check pull requests.

**Comment by tsuchm** [comment]
As shown in https://travis-ci.com/emacs-w3m/emacs-w3m/requests, the #12 PR was ignored.  I need to clarify this reason.

**Comment by Boruch-Baum** [comment]
I'm not knowledgeable in travis, but I thought maybe it wasn't running because the #12 had a merge conflict, so I did an internet search based upon that premise, and confirmed [that is the case](https://docs.travis-ci.com/user/pull-requests):

> If a pull request isn’t built or doesn’t show up in Travis CI’s user interface, that usually means that it can’t be merged. We rely on the merge commit that GitHub transparently creates between the changes in the source branch and the upstream branch the pull request is sent against.

There's more of interest on that page.

Also:

- [related question on stackexchange](https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda)

- [conditional travis builds](https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Conditional-Builds)

**Comment by Boruch-Baum** [comment]
Maybe I should stop being lazy and finally learn this 'travis' thing... If it can perform post-build unit tests, that would be great for a project as complex as emacs-w3m. For example, on every PR, run a full suite of emas-w3m operations on local URIs, check for pass/fail, a diff of content results, a major change in resource usage or run-time.

**Comment by tsuchm** [comment]
You can see the current configuration of Travis-CI for emacs-w3m at https://github.com/emacs-w3m/emacs-w3m/blob/master/.travis.yml.  The current configuration invokes make command only, thus it can detect byte-compile errors.  Of course, we will be able to create additional test sets as you proposed.

Anyway, I hope you will resolve conflicts.

**Comment by Boruch-Baum** [comment]
I see the same thing happening for the other outstanding pull requests, #2 and #4. In those cases also, it was just the changelog file that was stopping travis. I resolved both of those cases as well, but it points out one of the weaknesses in the travis workflow: a merge conflict in a file such as the changelog shouldn't block or stop the process; that kind of file will probably be edited anyway after travis succeeds and a pull request is approved. For example, the submission date and sequences of entries may be altered. Another example is when multiple pull requests are pending - travis will at first approve all, but then when the each is actually merged, travis will fail all the others because of the new changelog entry!

**Comment by Boruch-Baum** [comment]
I was bothered that travis was only using emacs 25, and with an OS from 2016, so I decided to see how other emacs projects use travis. Here are some links to .travis.yml files:

-  https://github.com/abo-abo/swiper/blob/master/.travis.yml
 - https://github.com/vermiculus/sx.el/blob/master/.travis.yml

This is all new and untested to me, but the current list for what [EVM](https://github.com/rejeep/evm) supports seems to be [here](https://github.com/rejeep/evm/tree/master/recipes), and seems to include emacs 26, the emacs development snapshot (I guess that's emacs 27), and something called `remacs` which seems to be a port of emacs written in rust.

As for operating system versions, if I'm reading correctly, travis seems to be moving to prefer use of docker images, so that may be why the 'native' operating systems that they're offering are so old. If that's true, then it should be easy to find and use a more recent image; however, neither of the two travis yaml files that I pseudo-randomly selected seem to be using that technique.

**Comment by tsuchm** [comment]
I got the current status of emacs-w3m Travis configuration, and believe it works.
